services:
  database:
    build:
      context: ./docker/database
    image: documents-postgres-age:pg17
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - database-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-example}
      - POSTGRES_DB=${POSTGRES_DB:-documents}
    restart: unless-stopped

volumes:
  database-data:
